apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  labels:
    app: angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: nginx
          image: ghcr.io/fredx30/hello-world-docker-angular:master
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app
spec:
  selector:
    app.kubernetes.io/name: angular-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
